# Generated by Django 4.1.7 on 2023-03-26 07:48

import cmsmain.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsmain', '0002_rename_user_name_projects_user_fname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='user_image',
            field=models.ImageField(default='profile_pic/image.jpg', upload_to=cmsmain.models.image_path),
        ),
        migrations.AlterField(
            model_name='projects',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2023, 3, 26, 7, 48, 56, 603069, tzinfo=datetime.timezone.utc)),
        ),
    ]
